### ISSUE TITLE
ドキュメントのアイデア

### ISSUE THREAD

**Issue by ytsuboi** [SeeedJP/Wio_3G_for_Arduino#1]
Wio LTE→Wio 3G移行ガイド

- SerialUSB.begin()が必要

**Comment by ytsuboi** [comment]
充電LEDの点灯について説明

**Comment by matsujirushi** [comment]
https://github.com/SeeedJP/Wiki/commit/0889217cefce4f3a97757fecf5d8f08d88ffefb6
