### ISSUE TITLE
マイコンのスリープ機能

### ISSUE THREAD

**Issue by tanihito** [SeeedJP/Wio_3G_for_Arduino#4]
Wio 3Gの消費電力を削減するために、マイコンのスリープや外部割り込み用の関数を追加していただけないでしょうか？

**Comment by matsujirushi** [comment]
外部割込みは、具体的のどの要因の外部割込みを使用したいのでしょうか？
https://github.com/SeeedJP/SeeedJP_STM32F4/blob/master/cores/Arduino/Boards/STM324x9I_EVAL/startup_stm32f439xx.S

**Comment by tanihito** [comment]
想定ユースケースとしては、 以下の2種類を考えております。
1. Grove コネクターにボタンや磁石スイッチを接続。ボタン/スイッチが作動すると動作する
2. タイマーで定期的に動作する

そのため、それぞれのユースケースに対応するであろう以下の外部割り込みを使用できれば、と思います。
1. EXTI3_IRQHandler, EXTI4_IRQHandler, EXTI9_5_IRQHandler
2. TIM2_IRQHandler
